# -*- coding: utf-8 -*-
"""BigMartSales_6(FE).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q-X-z9Ib62zn8oo4FzJW_X5KAHQAKTJ0
"""

! pip install optuna
! pip install mlflow

"""# BigMartSales

Imports and Global Configs
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import GradientBoostingRegressor

import optuna
import mlflow
import mlflow.sklearn

RANDOM_STATE = 42
N_SPLITS = 5

mlflow.set_experiment("BigMartSales_Prediction")

"""Data Loading"""

train = pd.read_csv("/content/train_v9rqX0R.csv")
test = pd.read_csv("/content/test_AbJTz2l.csv")

test_ids = test[["Item_Identifier", "Outlet_Identifier"]].copy()

print(train.shape, test.shape)

"""Feature Engineering Pipeline"""

def feature_engineering(train, test):

    train = train.copy()
    test = test.copy()

    # Handling Missing Item Weight
    item_weight_median = train.groupby("Item_Type")["Item_Weight"].median()

    for df in [train, test]:
        df["Item_Weight"] = df.apply(
            lambda x: item_weight_median[x["Item_Type"]]
            if pd.isnull(x["Item_Weight"]) else x["Item_Weight"],
            axis=1
        )

    # Visibility Handling

    train.loc[train["Item_Visibility"] == 0, "Item_Visibility"] = np.nan
    test.loc[test["Item_Visibility"] == 0, "Item_Visibility"] = np.nan

    visibility_median = train.groupby("Item_Type")["Item_Visibility"].median()

    for df in [train, test]:
        df["Item_Visibility"] = df.apply(
            lambda x: visibility_median[x["Item_Type"]]
            if pd.isnull(x["Item_Visibility"]) else x["Item_Visibility"],
            axis=1
        )

    # Fat Content Normalize + Binary Encoding

    mapping = {
        "lf": "Low Fat",
        "low fat": "Low Fat",
        "reg": "Regular",
        "regular": "Regular"
    }

    for df in [train, test]:
        df["Item_Fat_Content"] = (
            df["Item_Fat_Content"]
            .astype(str)
            .str.strip()
            .str.lower()
            .replace(mapping)
        )

    fat_encoding = {"Low Fat": 1, "Regular": 0}

    for df in [train, test]:
        df["Item_Fat_Content"] = df["Item_Fat_Content"].replace(fat_encoding)

    # Outlet Age Generation

    CURRENT_YEAR = 2013
    for df in [train, test]:
        df["Outlet_Age"] = CURRENT_YEAR - df["Outlet_Establishment_Year"]

    train.drop(columns=["Outlet_Establishment_Year"], inplace=True)
    test.drop(columns=["Outlet_Establishment_Year"], inplace=True)


    # Visibility Ratio

    visibility_mean = train.groupby("Item_Type")["Item_Visibility"].transform("mean")
    train["Visibility_Ratio"] = train["Item_Visibility"] / visibility_mean

    visibility_map = train.groupby("Item_Type")["Item_Visibility"].mean()
    test["Visibility_Ratio"] = test["Item_Visibility"] / test["Item_Type"].map(visibility_map)


    # MRP Binning
    bins = [0, 70, 140, 210, 300]

    train["MRP_Bin"] = pd.cut(train["Item_MRP"], bins=bins, labels=False)
    test["MRP_Bin"] = pd.cut(test["Item_MRP"], bins=bins, labels=False)

    # Interaction Feature

    train["Item_Outlet_Type"] = train["Item_Type"] + "_" + train["Outlet_Type"]
    test["Item_Outlet_Type"] = test["Item_Type"] + "_" + test["Outlet_Type"]

    return train, test

"""Kfold Encoding"""

def kfold_target_encoding(train_df, test_df, column, target, n_splits=5):

    train_encoded = pd.Series(index=train_df.index, dtype=float)
    global_mean = train_df[target].mean()

    kf = KFold(n_splits=n_splits, shuffle=True, random_state=RANDOM_STATE)

    for train_idx, val_idx in kf.split(train_df):
        fold_train = train_df.iloc[train_idx]
        fold_val = train_df.iloc[val_idx]

        means = fold_train.groupby(column)[target].mean()
        train_encoded.iloc[val_idx] = fold_val[column].map(means)

    train_encoded.fillna(global_mean, inplace=True)

    full_means = train_df.groupby(column)[target].mean()
    test_encoded = test_df[column].map(full_means)
    test_encoded.fillna(global_mean, inplace=True)

    return train_encoded, test_encoded

"""Prepare Modeling Data"""

def build_dataset(train, test):

    train, test = feature_engineering(train, test)

    # Target encoding
    train["Item_TE"], test["Item_TE"] = kfold_target_encoding(
        train, test, "Item_Identifier", "Item_Outlet_Sales"
    )

    train["Outlet_TE"], test["Outlet_TE"] = kfold_target_encoding(
        train, test, "Outlet_Identifier", "Item_Outlet_Sales"
    )

    # Drop high-card columns
    train.drop(columns=["Item_Identifier", "Outlet_Identifier"], inplace=True)
    test.drop(columns=["Item_Identifier", "Outlet_Identifier"], inplace=True)

    # One hot encode remaining categoricals
    train = pd.get_dummies(train, drop_first=True)
    test = pd.get_dummies(test, drop_first=True)

    train, test = train.align(test, join="left", axis=1, fill_value=0)

    y = train["Item_Outlet_Sales"]
    X = train.drop("Item_Outlet_Sales", axis=1)

    return X, y, test

X, y, test_processed = build_dataset(train, test)

"""Model Evaluation Utility"""

def evaluate_model(model, X, y):
    kf = KFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)
    scores = []

    for train_idx, val_idx in kf.split(X):
        X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

        model.fit(X_tr, y_tr)
        preds = model.predict(X_val)
        rmse = np.sqrt(mean_squared_error(y_val, preds))
        scores.append(rmse)

    return np.mean(scores)

"""Baseline MLflow Run"""

with mlflow.start_run(run_name="GB_TargetEncoding_Baseline"):

    model = GradientBoostingRegressor(
        n_estimators=600,
        learning_rate=0.03,
        max_depth=4,
        min_samples_leaf=5,
        subsample=0.8,
        random_state=RANDOM_STATE
    )

    cv_rmse = evaluate_model(model, X, y)

    mlflow.log_params(model.get_params())
    mlflow.log_metric("cv_rmse", cv_rmse)

    print("Baseline CV RMSE:", cv_rmse)

"""Optuna + MLflow Integration"""

def objective(trial):

    with mlflow.start_run(nested=True):

        params = {
            "n_estimators": trial.suggest_int("n_estimators", 200, 1000),
            "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1),
            "max_depth": trial.suggest_int("max_depth", 2, 6),
            "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 20),
            "subsample": trial.suggest_float("subsample", 0.6, 1.0),
            "random_state": RANDOM_STATE
        }

        model = GradientBoostingRegressor(**params)

        cv_rmse = evaluate_model(model, X, y)

        mlflow.log_params(params)
        mlflow.log_metric("cv_rmse", cv_rmse)

        return cv_rmse


study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=50)

print("Best CV:", study.best_value)
print("Best Params:", study.best_params)

test_processed = test_processed[X.columns]

best_model = GradientBoostingRegressor(
    **study.best_params,
    random_state=RANDOM_STATE
)

best_model.fit(X, y)

predictions = best_model.predict(test_processed)

submission = test_ids.copy()
submission["Item_Outlet_Sales"] = predictions

submission.to_csv("submission_v4.csv", index=False)

with mlflow.start_run(run_name="Leaderboard_Log"):
    mlflow.log_metric("leaderboard_score", 1157)

mlflow.search_runs()